name: Release TypeScript Package

on:
  push:
    tags:
      - 'ts-v*' # This will trigger on tags like ts-v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients/typescript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for release notes

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Generate release notes
        id: release
        run: |
          VERSION=${GITHUB_REF#refs/tags/ts-}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          # Extract changes from CHANGELOG if available, otherwise from git log
          if [ -f "../../CHANGELOG.md" ]; then
            CHANGES=$(awk -v ver="$VERSION" '/^## \['"$VERSION"'\]/{flag=1; next} /^## \[/{flag=0} flag' ../../CHANGELOG.md)
            if [ -z "$CHANGES" ]; then
              CHANGES=$(git log --pretty=format:"* %s (%h)" $(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD -- ./clients/typescript || echo "Initial release")
            fi
          else
            CHANGES=$(git log --pretty=format:"* %s (%h)" $(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD -- ./clients/typescript || echo "Initial release")
          fi
          echo "CHANGES<<EOF" >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: TypeScript Release ${{ steps.release.outputs.version }}
          body: |
            ## Changes in this TypeScript release
            
            ${{ env.CHANGES }}
            
            For full details, see the [CHANGELOG](https://github.com/lightfeed/lightfeed/blob/main/CHANGELOG.md).
          draft: false
          prerelease: false
